config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  root  "pages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :boards #, except: :show
  resources :articles
  get 'users/:user_id/boards/:id', to: 'boards#show'

  get "/:page" => "pages#show"

#  resources :users do
#    resources :boards, only: :show
#  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :image

end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  extend FriendlyId
  friendly_id :name, use: :slugged

  whitelist = ['image/png', 'image/jpeg', 'image/gif', 'video/mp4', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'video/x-matroska', 'video/webm' ]
 
  validates :image, presence: true, blob: { content_type: whitelist}

# Blacklist:
#   video/x-msvideo  # AVI
#   video/x-flv  # FLV

  
  def should_generate_new_friendly_id?
    slug.blank?  || name_changed?
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 before_action :authenticate_user!, :except => [ :show]

 def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :body, :image)
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, :except => [ :show]

  def index 
    @boards = Board.where(user_id: current_user.id).order(:name)
  end

  def show
    @board = Board.friendly.find(params[:id])
    expires_in 24.hours
    fresh_when(:etag => @board, :last_modified => @board.created_at.utc)
  end

  def new
    @board = Board.new
  end
  
  def edit
    @board = Board.friendly.find(params[:id])
  end

  def create
    @board = Board.new(board_params)
  
    if @board.save
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  def update
    @board = Board.friendly.find(params[:id])

    if @board.update(board_params)
      redirect_to action: "index"
    else
      render 'edit'
    end
  end

  def destroy
    @board = Board.friendly.find(params[:id])
    @board.destroy

    redirect_to action: "index"
  end

  private
    def board_params
      params.require(:board).permit(:name, :image, :resolution, :user_id)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @article = Article.first
  end

  def show
    render params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <% if  @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %>
          prohibited this Board from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :image %>
    <%= form.file_field :image %>
    .jpg .gif .png .pdf
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<%= render 'shared/header' %>
<div class="container">
<h1> Edit Article </h1>

<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<%= render 'shared/header' %>
<div class="card" style=" width: 32rem; height:44rem;">
  <div class="card-body">
    <%= link_to '+', new_article_path, class:"btn btn-info" %>
  </div>
</div>

<% @articles.each do |article| %>
<div class="card" style=" width: 32rem; height:44rem;">
<div style="display: none;"><%= article.image.content_type %></div>
<% case article.image.content_type
  when /image*/ %>
    <%= image_tag((article.image.variant(resize: "300x300") if article.image.attached?),  :class => "card-img-top") %>
  <% when /video*/ %>
    <%= video_tag((url_for(article.image) if article.image.attached?), class:"card-img-top") %>
  <% when /application*/ %>
    <%= image_tag((article.image.blob.preview(resize: "300X300") if article.image.blob.previewable?), :class => "card-img-top") %>
  <% else %>
    <%= article.image.content_type %>
    <%= link_to 'Back', articles_path %>
<% end %>


  <div class="card-body">
    <h2 class="card-title" style="overflow:auto; white-space:nowrap;"><%= article.title %></h2>
    <%= link_to 'Edit', edit_article_path(article), :class => "btn btn-secondary btn-sm" %>
    <%= link_to 'X', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger btn-sm" %><br><br>
  </div>
</div>
<% end %>

app/views/articles/new.html.erb
<%= render 'shared/header' %>
<div class="container">
  <h2>New article</h2>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<%= link_to 'Edit', edit_article_path(@article.id) %>
<%= link_to 'Destroy', article_path(@article.id), method: :delete, data: { confirm: 'Are you sure?' } %>

<h2><%= @article.title %></h2>
<br>
<%= @article.body.html_safe %>

app/views/boards/_form.html.erb
<%= form_with model: @board, local: true do |form| %>
  <% if  @board.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@board.errors.count, "error") %>
          prohibited this Board from being saved:
      </h2>
      <ul>
        <% @board.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :image %>
    <%= form.file_field :image %>
    .jpg .gif .png .mp4 .doc .docx .ppt .pptx .xls .xlsx .pdf
  </p>
  <p>
    <%= form.label :resolution %>
    <%= form.text_field :resolution %>
    Ex: 1920x1080
  </p>
  <p>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/boards/edit.html.erb
<%= render 'shared/header' %>
<div class="container">
<h1> Edit Screen </h1>

<%= render 'form' %>
</div>

app/views/boards/index.html.erb
<%= render 'shared/header' %>
<p><input id="gfg" type="text" placeholder="Search here"></p>
<% @boards.each do |board| %>
<div id="geeks"> 
<div class="card" style=" width: 32rem; height:44rem;">
<div style="display: none;"><%= board.image.content_type %></div>
<% case board.image.content_type
  when /image*/ %>
    <%= image_tag((board.image.representation(resize_to_limit: [300, 300]) if board.image.representable?),  :class => "card-img-top") %>
  <% when /video*/ %>
    <% if board.image.representable? %>
      <%= video_tag(url_for(board.image), class:"card-img-top") %>
    <% end %>
  <% when /application*/ %>
    <% if board.image.representable? %>
      <%= image_tag(board.image.blob.representation(resize_to_limit:[300, 300]), :class => "card-img-top") %>
    <% end %>
  <% else %>
    <%= board.image.content_type %>
    <%= link_to 'Back', boards_path %>
<% end %>


  <div class="card-body">
    <h2 class="card-title" style="overflow:auto; white-space:nowrap;"><%= board.name %></h2>
    <%= link_to 'Full Screen', "http://#{ENV['HOSTNAME']}/users/#{current_user.id}/boards/#{board.slug}", :class => "btn btn-primary btn-sm" %>
    <%# link_to 'Full Screen', board_path(board), :class => "btn btn-primary btn-sm" %>
    <%= link_to 'Edit', edit_board_path(board), :class => "btn btn-secondary btn-sm" %>
    <%= link_to 'Download', rails_blob_path(board.image, disposition: "attachment"), :class => "btn btn-secondary btn-sm" %>
    <%= link_to 'X', board_path(board), method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger btn-sm" %><br><br>
    <pre class="code" id="code" style="overflow: auto; width: auto;"><%= "http://#{ENV['HOSTNAME']}/users/#{current_user.id}/boards/#{board.slug}" %></pre>
    <button onclick="copyToClipboard('#code')">Copy</button>
  </div>
</div>
</div>
<% end %>
<script>
function copyToClipboard(element) {
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val($(element).text()).select();
    document.execCommand("copy");
    $temp.remove();
}
</script>
<script> 
            $(document).ready(function() { 
                $("#gfg").on("keyup", function() { 
                    var value = $(this).val().toLowerCase(); 
                    $("#geeks .card").filter(function() { 
                        $(this).toggle($(this).text() 
                        .toLowerCase().indexOf(value) > -1) 
                    }); 
                }); 
            }); 
</script> 

app/views/boards/new.html.erb
<%= render 'shared/header' %>
<div class="container">
  <h2>Upload Screen</h2>
  <%= render 'form' %>
</div>

app/views/boards/show.html.erb
<% case @board.image.content_type
  when /image*/ %>
    <%= image_tag((@board.image.variant(resize: @board.resolution) if @board.image.attached?),  :class => "img-fluid") %>
  <% when /video*/ %>
    <%= video_tag(url_for(@board.image),controls: false, autoplay: true, muted: true, loop: true, class:"vid-fluid")  %>
  <% when /application*/ %>
    <%= image_tag @board.image.blob.preview(resize: "1920x1080"), :class => "img-fluid" %>
  <% else %>
    <%= link_to 'Back', boards_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picture in a Pi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/how_to.html.erb
<%= render 'shared/header' %>

app/views/pages/index.html.erb
<%= render 'shared/header' %>
<%= @article.body.html_safe %>

app/views/shared/_content_type.html.erb
<% case board.image.content_type
  when "image/png" %>
    <%= image_tag((board.image.variant(resize: "300x300") if board.image.attached?),  :class => "card-img-top") %>
  <% when "image/jpeg" %>
    <%= image_tag((board.image.variant(resize: "300x300") if board.image.attached?),  :class => "card-img-top") %>
  <% when "image/gif" %>
    <%= image_tag((board.image.variant(resize: "300x300") if board.image.attached?),  :class => "card-img-top") %>
  <% when "video/mp4" %>
    <%= video_tag(url_for(board.image), class:"card-img-top") %>
  <% else %>
    <%= link_to 'Back', boards_path %>
<% end %>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Picture in a Pi', root_path, class:"navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-li"><%= link_to 'My Screens', controller: '/boards' %></li>
        <li class="navbar-li"><%= link_to 'Upload', new_board_path, class:"btn btn-info" %></li>
        <% if user_signed_in? %>
          <li class="navbar-li"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li class="navbar-li"><%= link_to('Login', new_user_session_path) %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

</header>